baseURL = 'https://shokakko.com/'
languageCode = 'en-us'
title = "ReadTFB"
createdBy = "Olivier Girardot"

[module]
  [[module.imports]]
    disable = false
    ignoreConfig = false
    ignoreImports = true
    path = "github.com/LordMathis/hugo-theme-nightfall"

[markup.goldmark.renderer]
unsafe = true

[frontmatter]
#date = [':filename', ':default']

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "/posts"
  #[[menu.header]]
  #  name = "about"
  #  weight = 1
  #  url = "about"

[params]
footerHtml = 'CC-0, Built with <a href="https://gohugo.io" class="footerLink">Hugo</a> and <a href="https://github.com/LordMathis/hugo-theme-nightfall" class="footerLink">Nightfall</a> theme <script defer async src="https://tracker.blogtally.com/blogtally.min.js" data-site="407d5903-3398-4e8b-afae-cdbd24bf6da5" data-link-tracking="true"></script>'
user = "ogirardot"
hostname = "readtfb.com"
sitedescription = 'Olivier Girardot personal blog'
sitename = "ReadTFB | Olivier Girardot"

[params.author]
name = "Olivier Girardot"  # Website and RSS feed author

[params.styles]
color = "orange"

readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
key = 0
name = "github"
url = "https://github.com/ogirardot"
target = "_blank"
aria = "GitHub Profile"

[[params.social]]
key = 1
name = "bluesky"
url = "https://bsky.app/profile/ogirardot.bsky.social"
aria = "Bluesky Profile"

[[params.social]]
key = 2
name = "linkedin"
url = "https://www.linkedin.com/in/oliviergirardot"
aria = "LinkedIn Profile"

# Add these settings for image handling
[imaging]
quality = 75
resampleFilter = "Lanczos"

[security]
enableInlineShortcodes = true

[security.funcs]
getenv = ['^HUGO_']
  
